/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Record({
  'testCategory' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'gradeLevel' : IDL.Text,
});
export const Flashcard = IDL.Record({
  'id' : IDL.Nat,
  'front' : IDL.Text,
  'testCategory' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'back' : IDL.Text,
  'gradeLevel' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'testCategory' : IDL.Opt(IDL.Text),
  'question' : IDL.Text,
  'subject' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'gradeLevel' : IDL.Text,
  'choices' : IDL.Vec(IDL.Text),
});
export const UserProgress = IDL.Record({
  'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'reviewedFlashcards' : IDL.Vec(IDL.Nat),
  'dailyStudyStreak' : IDL.Nat,
  'totalStudyTime' : IDL.Nat,
  'lastStudyDate' : IDL.Int,
});

export const idlService = IDL.Service({
  'addFlashcard' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addQuizQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getFlashcardsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'getQuizQuestionsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuizQuestion)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
  'seedData' : IDL.Func([], [], []),
  'updateUserProgress' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Record({
    'testCategory' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'gradeLevel' : IDL.Text,
  });
  const Flashcard = IDL.Record({
    'id' : IDL.Nat,
    'front' : IDL.Text,
    'testCategory' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'back' : IDL.Text,
    'gradeLevel' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'testCategory' : IDL.Opt(IDL.Text),
    'question' : IDL.Text,
    'subject' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'gradeLevel' : IDL.Text,
    'choices' : IDL.Vec(IDL.Text),
  });
  const UserProgress = IDL.Record({
    'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'reviewedFlashcards' : IDL.Vec(IDL.Nat),
    'dailyStudyStreak' : IDL.Nat,
    'totalStudyTime' : IDL.Nat,
    'lastStudyDate' : IDL.Int,
  });
  
  return IDL.Service({
    'addFlashcard' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addQuizQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getFlashcardsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'getQuizQuestionsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([IDL.Principal], [UserProgress], ['query']),
    'seedData' : IDL.Func([], [], []),
    'updateUserProgress' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };