/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Flashcard {
  'id' : bigint,
  'front' : string,
  'testCategory' : [] | [string],
  'subject' : string,
  'back' : string,
  'gradeLevel' : string,
}
export interface QuizQuestion {
  'id' : bigint,
  'testCategory' : [] | [string],
  'question' : string,
  'subject' : string,
  'correctAnswer' : bigint,
  'gradeLevel' : string,
  'choices' : Array<string>,
}
export interface Subject {
  'testCategory' : [] | [string],
  'name' : string,
  'gradeLevel' : string,
}
export interface UserProgress {
  'quizScores' : Array<[string, bigint]>,
  'reviewedFlashcards' : Array<bigint>,
  'dailyStudyStreak' : bigint,
  'totalStudyTime' : bigint,
  'lastStudyDate' : bigint,
}
export interface _SERVICE {
  'addFlashcard' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'addQuizQuestion' : ActorMethod<
    [string, Array<string>, bigint, string, string, [] | [string]],
    undefined
  >,
  'addSubject' : ActorMethod<[string, string, [] | [string]], undefined>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getFlashcardsBySubject' : ActorMethod<[string], Array<Flashcard>>,
  'getQuizQuestionsBySubject' : ActorMethod<[string], Array<QuizQuestion>>,
  'getUserProgress' : ActorMethod<[Principal], UserProgress>,
  'seedData' : ActorMethod<[], undefined>,
  'updateUserProgress' : ActorMethod<
    [Array<bigint>, Array<[string, bigint]>, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];